M48
; DRILL file {KiCad (6.0.5)} date Fri Jul 22 19:18:11 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-22T19:18:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X58.928Y-25.908
X58.928Y-169.672
X124.968Y-25.908
X124.968Y-169.672
T0
M30
